<a href="https://colab.research.google.com/github/sendmail123/DataScience/blob/master/Recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [4]:
from google.colab import files
uploaded = files.upload()

Saving ratings.csv to ratings.csv

In [0]:
import io
df = pd.read_csv(io.BytesIO(uploaded['ratings.csv']))

In [0]:
userList=df['user'].unique()

In [0]:
userList.sort()

In [8]:
userList

array([   5,   10,   15, ..., 6030, 6035, 6040])

In [0]:
itemList=df['item'].unique()

In [0]:
itemList.sort()

In [11]:
itemList

array([   1,    2,    3, ..., 3950, 3951, 3952])

In [0]:
Movielens=pd.DataFrame(index=userList,
            columns=itemList)

In [13]:
Movielens.iloc[0:4,:3]

      1    2    3
5   NaN  NaN  NaN
10  NaN  NaN  NaN
15  NaN  NaN  NaN
20  NaN  NaN  NaN

In [0]:
a=0
for i in userList:
    for j in df[df['user']==i]['item']:
        Movielens.iloc[a][j]=df[(df['user']==i)&(df['item']==j)]['rating'].item()
    a=a+1

In [25]:
Movielens

     1    2    3    4    5    6    7     ... 3946 3947 3948 3949 3950 3951 3952
5     NaN  NaN  NaN  NaN  NaN    2  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
10      5    5  NaN  NaN  NaN  NaN    4  ...  NaN  NaN    4  NaN  NaN  NaN  NaN
15    NaN  NaN  NaN  NaN  NaN    4  NaN  ...  NaN  NaN    3  NaN  NaN  NaN  NaN
20    NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
25    NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
6020  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6025    5  NaN    3    3  NaN  NaN    4  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6030  NaN    4  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6035    4  NaN    1    2    1  NaN    3  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
6040    3  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[1208 rows x 3514 columns]

In [28]:
df[(df['user']==10) & (df['item']==3928)]

     user  item  rating
591    10  3928     4.0

In [23]:
df[(df['user']==5) & (df['item']==39)]['rating'].item()

3.0